apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-microservice-deployment
  labels:
    app: event-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-microservice
  template:
    metadata:
      labels:
        app: event-microservice
    spec:
      containers:
      - name: event-microservice
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/event-microservice:$VERSION
        env:
        - name: PORT
          value: "3400"
        - name: DB_USERNAME
          value: $DB_USERNAME
        - name: DB_PASSWORD
          value: $DB_PASSWORD
        - name: SESSION_SECRET
          value: $SESSION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: event-microservice
spec:
  type: LoadBalancer
  ports:
    - port: 3400
      targetPort: 3400
  selector:
    app: event-microservice
