apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-microservice-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-microservice
  minReplicas: 1 #min one pod
  maxReplicas: 3 #max 3 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 #If CPU usage exceeds 50%, system scales up, k8s adds more pods, and vice versa
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 75Mi  #Scale when average memory exceeds 75Mi
behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  #Wait 30s before scaling
      policies:
        - type: Percent
          value: 100 #Can double amount of pods
          periodSeconds: 20  #Check every 20s
    scaleDown:
      stabilizationWindowSeconds: 30  #Wait 30s before scaling
      policies:
        - type: Percent
          value: 100 #Can double amount of pods
          periodSeconds: 20  #Check every 20s
