apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
      - name: user-microservice
        image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/user-microservice:latest
        env:
        - name: PORT
          value: "3200"
        - name: DB_USERNAME
          value: $DB_USERNAME
        - name: DB_PASSWORD
          value: $DB_PASSWORD
        - name: SESSION_SECRET
          value: $SESSION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice
spec:
  type: LoadBalancer
  ports:
    - port: 3200
      targetPort: 3200
  selector:
    app: user-microservice

