apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
  namespace: default
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
      - name: user-microservice
        image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/user-microservice:latest
        env:
        - name: PORT
          value: "3200"
        startupProbe:
          exec:
            command:
              - cat
              - /tmp/started
          initialDelaySeconds: 5
          periodSeconds: 4
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 3200
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3200
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi 
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice
spec:
  type: LoadBalancer
  ports:
    - port: 3200
      targetPort: 3200
  selector:
    app: user-microservice

