apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: event-microservice-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-microservice
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 #If CPU usage exceeds 50%, system scales up, k8s adds more pods, and vice versa
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 75Mi #Scale when average memory exceeds 75Mi
behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 20
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 20
