apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/frontend:latest
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 126m
            memory: 1024Mi
          limits:
            cpu: 256m
            memory: 2048Mi 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: frontend

