name: CI/CD for Event Service

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
    paths:
      - 'backend/Microservices/Events/**'  # Trigger workflow when code in this path changes

  pull_request:
    branches:
      - main

  workflow_dispatch:



jobs:
  event-microservice:
    runs-on: ubuntu-latest

    env:
        VERSION: ${{ github.sha }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install Dependencies
        working-directory: backend/Microservices/Events
        run: npm ci

      - name: Run Tests
        working-directory: backend/Microservices/Events
        run: npm test  # Ensure you have test scripts in package.json


  docker-build-and-run:
    needs: event-microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
         docker build -t event_service:latest --file backend/Microservices/Events/Dockerfile .

      - name: Run Docker Container Locally
        run: |
          docker run -d -p 3200:3200 --name event_service event_service:latest

          