name: CI/CD for Gateway

on:
  push:
    branches:
      - main
      - external_routes
    paths:
      - 'backend/Microservices/Gateway/**' # Trigger workflow when code in this path changes
  
  pull_request:
    branches:
        - main


  workflow_dispatch:

env:
    VERSION: ${{ github.sha }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
    CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
    CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}


jobs:
  gateway:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'backend/Microservices/Gateway' 
    
 
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'


      - name: Install Dependencies
        working-directory: backend/Microservices/Gateway
        run: npm ci

      #- name: Run Tests
      #  run: npm test


  docker-build-and-run:
    needs: gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${CONTAINER_REGISTRY_LOGIN_SERVER}/gateway:latest -f backend/Microservices/Gateway/Dockerfile backend
        
      - name: Push Docker Image to Azure Container Registry
        working-directory: 'backend/Microservices/Gateway'
        run: |
            echo ${CONTAINER_REGISTRY_PASSWORD} | docker login ${CONTAINER_REGISTRY_LOGIN_SERVER} -u ${CONTAINER_REGISTRY_USERNAME} --password-stdin
            docker push ${CONTAINER_REGISTRY_LOGIN_SERVER}/gateway:latest


      - name: Install Kubectl
        uses: tale/kubectl-action@v1
        with:
            base64-kube-config: ${{ secrets.KUBE_CONFIG }}
            kubectl-version: v1.32.0


      - name: Deploy User Manifest to the AKS cluster (Azure Kubernetes Service)
        run: | 
            envsubst < backend/Microservices/Gateway/Kubernetes/gatewayDeployment.yml > gatewayDeployment.processed.yml
            kubectl apply -f gatewayDeployment.processed.yml


