name: CI/CD for Group Service

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
    paths:
      - 'backend/Microservices/Groups/**'  # Trigger workflow when code in this path changes

  pull_request:
    branches:
      - main

  workflow_dispatch:



env:
    VERSION: ${{ github.sha }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
    CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
    CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}



jobs:
  group-microservice:
    runs-on: ubuntu-latest

    defaults:
      run: 
        working-directory: 'backend/Microservices/Groups'


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install Dependencies
        working-directory: backend/Microservices/Groups
        run: npm ci



  docker-build-and-run:
    needs: group-microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4



      - name: Build Docker Image
        run: docker build -t ${CONTAINER_REGISTRY_LOGIN_SERVER}/group-microservice:latest -f backend/Microservices/Groups/Dockerfile backend
      


      - name: Push Docker Image to Azure Container Registry
        working-directory: 'backend/Microservices/Groups'
        run: |
          echo ${CONTAINER_REGISTRY_PASSWORD} | docker login ${CONTAINER_REGISTRY_LOGIN_SERVER} -u ${CONTAINER_REGISTRY_USERNAME} --password-stdin
          docker push ${CONTAINER_REGISTRY_LOGIN_SERVER}/group-microservice:latest



      #- name: Build Docker Image
      #  run: |
      #   docker build -t group_service:latest -f backend/Microservices/Groups/Dockerfile backend --no-cache

      #- name: Run Docker Container Locally
      #  run: |
      #    docker run -d -p 3600:3600 --name group_service group_service:latest

      - name: Install Kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.32.0


      - name: Deploy User Manifest to the AKS cluster (Azure Kubernetes Service)
        run: | 
          envsubst < Kubernetes_Manifests/groupDeployment.yml > groupDeployment.processed.yml
          kubectl apply -f groupDeployment.processed.yml

          